#!/do/not/exec/sh
export PATH=${PATH}:${PWD}
export PATH=${PATH}:${PWD}/bin
__bch9_warn () {
    tput setaf 1 
    tput setab 10 
    tput blink
    printf  "$*"
    tput sgr0
    echo
}

mkdir -p ~/.local/bin
echo 777 $PWD
echo }} ls $PWD
cp ./lbin/* ~/.local/bin

cd ./source.d
for script in $(/bin/ls [0-9]* | sort); do
    _myborg source  $PWD/$script
done
