#!/do/not/exec/sh

__lbin_default
#export PATH=${PATH}:$(dirname ${PWD})
#export PATH=${PATH}:$(dirname ${PWD})/bin
#export PATH=${PATH}:${PWD}/bin
__bch9_warn () {
    tput setaf 1 
    tput setab 10 
    tput blink
    printf  "$*"
    tput sgr0
    echo
}

#mkdir -p ~/.local/bin
#cp ../lbin/* ~/.local/bin

cd ../source.d
for script in $(/bin/ls [0-9]* | sort); do
    source  $PWD/$script
done
